services:
  actordemo:
    image: actordemo-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./pytwb_ws:/root/pytwb_ws:rw
    command: xterm -fn 12X24 -display ${DISPLAY} -T 'cm main'

